import { expect, it } from 'vitest';
import { BoxGeometry, Vector3 } from 'three';
import { createEditableMesh, meshPoint } from '@/lib/editableMesh';
import { editMeshSurface, expandMeshSelection } from '@/lib/meshEditOperations';
function cube() { const g = new BoxGeometry(20, 20, 20); return createEditableMesh(new Float32Array(g.attributes.position.array), new Uint32Array(g.index!.array)); }
function area(mesh: ReturnType<typeof cube>) { let area = 0; for (let t = 0; t < mesh.indices.length; t += 3) { const [a, b, c] = Array.from(mesh.indices.slice(t, t + 3)).map(id => meshPoint(mesh, id)); area += new Vector3().crossVectors(b.sub(a), c.sub(a)).length() / 2; } return area; }
it('inserts connected surface vertices without changing area or losing triangles', () => { const mesh = cube(), result = editMeshSurface(mesh, 'face', new Set([0]), 'poke'); expect(result.positions.length / 3).toBe(10); expect(result.indices.length / 3).toBe(16); expect(area(result)).toBeCloseTo(area(mesh)); expect(result.faces.flat().sort((a,b) => a-b)).toEqual(Array.from({length:16}, (_,i)=>i)); expect(mesh.positions.length / 3).toBe(8); });
it('triangulates polygon membership without changing geometry', () => { const mesh = cube(), result = editMeshSurface(mesh, 'face', new Set([0]), 'triangulate'); expect(result.faces.length).toBe(7); expect(result.indices).toEqual(mesh.indices); });
it('normal reversal is reversible and leaves other faces unchanged', () => { const mesh = cube(), flipped = editMeshSurface(mesh, 'face', new Set([0]), 'flip'); expect(flipped.indices).not.toEqual(mesh.indices); expect(editMeshSurface(flipped, 'face', new Set([0]), 'flip')).toEqual(mesh); });
it('linked selection traverses connectivity and grow expands one ring', () => { const mesh = cube(), start = new Set([0]); expect(expandMeshSelection(mesh, 'vertex', start, 'grow').size).toBe(4); expect(expandMeshSelection(mesh, 'vertex', start, 'linked').size).toBe(8); expect(expandMeshSelection(mesh, 'vertex', start, 'invert').size).toBe(7); });
it('smooth and flatten only change selected vertices', () => { const mesh = cube(); for (const action of ['smooth', 'flattenX'] as const) { const result = editMeshSurface(mesh, 'vertex', new Set([0, 7]), action); for (let id = 1; id < 7; id++) expect(meshPoint(result, id)).toEqual(meshPoint(mesh, id)); expect(result.positions).not.toEqual(mesh.positions); } });
