import { describe,it,expect } from 'vitest';
import { BoxGeometry,Matrix4,Vector3 } from 'three';
import { createEditableMesh,editableEdges,meshPoint,selectionCenter,selectionVertices } from '@/lib/editableMesh';
import { knifeFace,loopCut,insetFaces,bevelEdges,weldVertices,dissolveEdges,polygonLoop,edgeKey } from '@/lib/meshPolygonTools';
import { influenceWeights,assistedTransform,symmetryPairs,snapPosition } from '@/lib/meshTransformAssist';
function cube(){const g=new BoxGeometry(20,20,20);return createEditableMesh(new Float32Array(g.attributes.position.array),new Uint32Array(g.index!.array));}
function area(m:ReturnType<typeof cube>){let result=0;for(let t=0;t<m.indices.length;t+=3){const [a,b,c]=Array.from(m.indices.slice(t,t+3),id=>meshPoint(m,id));result+=b.sub(a).cross(c.sub(a)).length()/2;}return result;}
function volume(m:ReturnType<typeof cube>){let result=0;for(let t=0;t<m.indices.length;t+=3){const [a,b,c]=Array.from(m.indices.slice(t,t+3),id=>meshPoint(m,id));result+=a.dot(b.cross(c))/6;}return result;}
function closed(m:ReturnType<typeof cube>){const edges=new Map<string,{count:number;balance:number}>();for(let t=0;t<m.indices.length;t+=3)for(let j=0;j<3;j++){const a=m.indices[t+j],b=m.indices[t+(j+1)%3],key=edgeKey(a,b),entry=edges.get(key)??{count:0,balance:0};entry.count++;entry.balance+=a<b?1:-1;edges.set(key,entry);}expect([...edges.entries()].filter(([,e])=>e.count!==2||e.balance!==0)).toEqual([]);expect(m.faces.flat().sort((a,b)=>a-b)).toEqual(Array.from({length:m.indices.length/3},(_,i)=>i));expect([...m.positions].every(Number.isFinite)).toBe(true);}
describe('surface tools',()=>{
  it('knife splits face and neighbors without T junctions or changing volume',()=>{const m=cube(),loop=polygonLoop(m,0),a=meshPoint(m,loop[0]).lerp(meshPoint(m,loop[1]),.5),b=meshPoint(m,loop[2]).lerp(meshPoint(m,loop[3]),.5),cut=knifeFace(m,0,a,b);expect(cut.faces.length).toBe(7);expect(cut.positions.length/3).toBe(10);expect(area(cut)).toBeCloseTo(area(m));expect(volume(cut)).toBeCloseTo(volume(m));closed(cut);expect(m.faces.length).toBe(6);});
  it('loop crosses a closed quad strip and slides without changing volume',()=>{const m=cube();for(const t of [.2,.5,.8]){const cut=loopCut(m,editableEdges(m)[0],t);expect(cut.faces.length).toBe(10);expect(cut.positions.length/3).toBe(12);expect(volume(cut)).toBeCloseTo(volume(m));closed(cut);}});
  it('inset adds ring of joined faces and preserves the surface',()=>{const m=cube(),result=insetFaces(m,new Set([0]),2);expect(result.faces.length).toBe(10);expect(area(result)).toBeCloseTo(area(m));expect(volume(result)).toBeCloseTo(volume(m));closed(result);expect(()=>insetFaces(m,new Set([0]),11)).toThrow();});
  it('bevel single or all cube edges makes a smaller closed solid',()=>{const m=cube();for(const edges of [[editableEdges(m)[0]],editableEdges(m)])for(const segments of [1,3]){const result=bevelEdges(m,edges,2,segments);expect(volume(result)).toBeGreaterThan(0);expect(volume(result)).toBeLessThan(volume(m));try { closed(result); } catch(e) { throw new Error(JSON.stringify({edges:edges.length,segments})+String(e)); }}});
  it('weld removes duplicate vertices and degenerate triangles without mutating source',()=>{const m=cube(),original=m.positions.slice(),edge=editableEdges(m)[0],result=weldVertices(m,new Set([edge.a,edge.b]),null);expect(result.positions.length/3).toBe(7);expect(m.positions).toEqual(original);expect(()=>weldVertices(m,new Set([edge.a,edge.b]),.01)).toThrow();});
  it('dissolve removes cut boundary while preserving exact triangles',()=>{const m=cube(),loop=polygonLoop(m,0),cut=knifeFace(m,0,meshPoint(m,loop[0]).lerp(meshPoint(m,loop[1]),.5),meshPoint(m,loop[2]).lerp(meshPoint(m,loop[3]),.5));const newEdges=editableEdges(cut),edge=newEdges.find(e=>{const a=meshPoint(cut,e.a),b=meshPoint(cut,e.b);return a.distanceTo(b)>19&&Math.abs(a.y-b.y)<1e-5&&Math.abs(a.z-b.z)>19;});const coplanar=newEdges.filter(e=>{try{return dissolveEdges(cut,[e]).faces.length===6;}catch{return false;}});expect(coplanar.length).toBeGreaterThan(0);const result=dissolveEdges(cut,[coplanar[0]]);expect(result.indices).toEqual(cut.indices);closed(result);expect(()=>dissolveEdges(m,[editableEdges(m)[0]])).toThrow();});
});
describe('transform assistance',()=>{
  it('proportional falloff affects nearby points and leaves points outside radius untouched',()=>{const base=new Float32Array([0,0,0,5,0,0,20,0,0]),output=base.slice(),weights=influenceWeights(base,[0],10);assistedTransform(base,output,new Matrix4().makeTranslation(0,10,0),weights,[],'off');expect(output[1]).toBe(10);expect(output[4]).toBe(5);expect(output[7]).toBe(0);});
  it('symmetry reflects selected deltas into matched opposite vertices',()=>{const base=new Float32Array([-2,0,0,2,0,0,0,1,0]),output=base.slice();assistedTransform(base,output,new Matrix4().makeTranslation(1,3,0),influenceWeights(base,[1],0),symmetryPairs(base,'x',0),'x');expect([...output]).toEqual([-3,3,0,3,3,0,0,1,0]);});
  it('snaps to grid, fixed vertices and closest points on fixed edges',()=>{const base=new Float32Array([0,0,0,10,0,0]);expect(snapPosition(new Vector3(2.4,3.7,0),base,[],new Set(),'grid',1,2).toArray()).toEqual([2,4,0]);expect(snapPosition(new Vector3(.1,0,0),base,[],new Set(),'vertex',1,1).toArray()).toEqual([0,0,0]);expect(snapPosition(new Vector3(4,1,0),base,[{a:0,b:1}],new Set(),'edge',1,2).toArray()).toEqual([4,0,0]);expect(snapPosition(new Vector3(.1,0,0),base,[],new Set([0]),'vertex',1,1).x).toBe(.1);});
});

it("distance welding joins nearby duplicate corners and preserves a closed cube",()=>{
 const m=cube(),positions=new Float32Array(m.positions.length+3);positions.set(m.positions);positions.set(m.positions.slice(0,3),m.positions.length);positions[m.positions.length]+=.0001;const indices=m.indices.slice();indices[0]=m.positions.length/3;
 const result=weldVertices({...m,positions,indices},new Set([0,m.positions.length/3]),.001);expect(result.positions.length/3).toBe(8);closed(result);
});
it("inset does not retriangulate an unrelated bent face",()=>{
 const m=cube(),face=0,chosen=new Set(selectionVertices(m,"face",new Set([face]))),other=Array.from({length:m.positions.length/3},(_,i)=>i).find(i=>!chosen.has(i));m.positions[other!*3+1]+=3;
 const result=insetFaces(m,new Set([face]),1);expect(area(result)).toBeCloseTo(area(m),3);expect(volume(result)).toBeCloseTo(volume(m),3);closed(result);
});
